<?php

class sposobNadaniaType
{
    const __default = 'WERYFIKACJA_WEZEL_DOCELOWY';
    const WERYFIKACJA_WEZEL_DOCELOWY = 'WERYFIKACJA_WEZEL_DOCELOWY';
    const WERYFIKACJA_WEZEL_NADAWCZY = 'WERYFIKACJA_WEZEL_NADAWCZY';


}
