services:
    bitbag.poczta_polska_shipping_export_plugin.form.type.poczta_polska_shipping_gateway:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Form\Type\ShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'poczta_polska', label: "Poczta Polska" }

    bitbag.poczta_polska_shipping_export_plugin.event_listener.poczta_polska_shipping_export:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@filesystem'
            - '@bitbag.repository.shipping_export'
            - '%bitbag.shipping_labels_path%'
            - '@bitbag.poczta_polska_shipping_export_plugin.api.web_client'
            - '@session.flash_bag'
            - '@bitbag.poczta_polska_shipping_export_plugin.export_file_provider'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    bitbag.poczta_polska_shipping_export_plugin.api.web_client:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Api\WebClient

    bitbag.poczta_polska_shipping_export_plugin.export_file_provider:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\EventListener\ShippingExportEventListener\ShippingExportFileProvider
