services:
    bitbag.poczta_polska_shipping_export_plugin.form.type.poczta_polska_shipping_gateway:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Form\Type\ShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'poczta_polska', label: "Poczta Polska" }

    bitbag.poczta_polska_shipping_export_plugin.event_listener.poczta_polska_shipping_export:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@filesystem'
            - '@bitbag.repository.shipping_export'
            - '%bitbag.shipping_labels_path%'
            - '@bitbag.poczta_polska_shipping_export_plugin.api.web_client'
            - '@session.flash_bag'
            - '@bitbag.poczta_polska_shipping_export_plugin.file_name_generator'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    bitbag.poczta_polska_shipping_export_plugin.api.web_client:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Api\WebClient
        arguments:
            - '@bitbag.poczta_polska_shipping_export_plugin.guid_generator'
            - '@bitbag.poczta_polska_shipping_export_plugin.label_parameters_factory'
            - '@bitbag.poczta_polska_shipping_export_plugin.shipment_factory'
            - '@bitbag.poczta_polska_shipping_export_plugin.address_factory'
            - '@bitbag.poczta_polska_shipping_export_plugin.package_factory'

    bitbag.poczta_polska_shipping_export_plugin.file_name_generator:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Generator\FileNameGenerator

    bitbag.poczta_polska_shipping_export_plugin.guid_generator:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Generator\GuidGenerator

    bitbag.poczta_polska_shipping_export_plugin.label_parameters_factory:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Factory\LabelParametersFactory

    bitbag.poczta_polska_shipping_export_plugin.shipment_factory:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Factory\ShipmentFactory

    bitbag.poczta_polska_shipping_export_plugin.package_factory:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Factory\PackageFactory
        arguments:
            - '@bitbag.poczta_polska_shipping_export_plugin.payment_checker'

    bitbag.poczta_polska_shipping_export_plugin.address_factory:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Factory\AddressFactory

    bitbag.poczta_polska_shipping_export_plugin.payment_checker:
        class: BitBag\SyliusPocztaPolskaShippingExportPlugin\Checker\PaymentChecker
